### ISSUE TITLE
mouse scroll on mac

### ISSUE THREAD

**Issue by josephholsten** [driusan/de#12] opened 2016-06-08 21:01 UTC
it would be nice to be able to scroll through a buffer using my mouse.

**Comment by driusan** [comment] 2016-06-08 23:34
I think this should be fixed. Can you pull the latest code and see if it works for you?

**Comment by josephholsten** [comment] 2016-06-09 00:03
seriously, you implemented my feature request too quickly. It kinda sorta works now.

Unfortunately, window redraw seems to lag by quite a bit, so motion continues long after I've stopped scrolling.

**Comment by driusan** [comment] 2016-06-09 02:10
It's been annoying me at work where I have a Mac, so I'd been meaning to look into it anyways.

I'll see if I have the same problems with the redraw/lag when I'm at work tomorrow and if there's anything obvious I can do about it while I'm physically at a Mac (other than trying to optimize the rendering code more..)

**Comment by driusan** [comment] 2016-06-09 14:06
Okay, I'm definitely seeing the lag too. I think, other than the obvious fact that I need to optimize the rendering code, it might be that the shiny driver for Mac is sending the mouse wheel events at weird rates, because I'm also noticing things like it not sending any event if I scroll one click (or just in general if I scroll too slowly with the wheel), and the events are in the opposite direction of what the system preferences say it should be (golang/go#16020)

I'll try digging into it tonight and see if there's something wrong in my code or if I notice anything obviously with the driver (though that's unlikely since I don't really know objective C..)

(/cc @nigeltao FYI)

**Comment by nigeltao** [comment] 2016-06-17 01:07
@crawshaw for mouse wheel weirdness on Mac shiny.

@driusan, are scroll events from the touch pad (instead of a mouse) OK?

**Comment by shurcooL** [comment] 2016-06-17 01:22
@nigeltao Is there a event linter (testing program) for shiny? It might be easier and more direct to test on that. Something like `go get -u github.com/goxjs/glfw/tests/events`.

I tried `de` on OS X and the scrolling seems **equally** broken/laggy and not-smooth using both a mouse scroll wheel and a magic trackpad. But I can't be sure how much of that is due to shiny events, and how much due to `de`'s logic on top.

**Comment by driusan** [comment] 2016-06-17 01:48
@shurcooL that's basically what the shiny `examples/basic` program does, which is why I filed the upstream report based on the behaviour there instead of in `de`.

I'll try and see how things work with the trackpad tomorrow when I'm at my Mac, but it's harder to say definitively since there's no discrete "clicks" that should definitively cause/not cause an event with a trackpad

**Comment by shurcooL** [comment] 2016-06-17 02:20
Ok, I tried `examples/basic`, and I can confirm that the scroll events from touch pad are abou equivalent as from mouse, not better. Events from the mouse scroll wheel are not great.

Scrolling down maps to button -1, and scrolling up maps to button -2. But there's no 1 to 1 mapping from scroll wheel to event. Instead, if you move the scroll wheel slowly, it takes about 10 scroll clicks before a single button event is generated. If you move it quickly, due to scrolling acceleration, you get many -1 button events all at once.

**Comment by driusan** [comment] 2016-06-17 13:56
@nigeltao/@crawshaw Okay, a little more digging: the events on the trackpad are also screwed up. I added a note to golang/go#16020 about the trackpad and mouse system settings interacting in shiny, but as far as this issue goes: the trackpad seems *far* too sensitive, and the mouse either not sensitive enough or too sensitive depending on how fast you scroll the wheel.

```
got mouse.Event{X:912, Y:603, Button:-2, Modifiers:0x0, Direction:0x0}
got mouse.Event{X:912, Y:603, Button:-2, Modifiers:0x0, Direction:0x0}
got mouse.Event{X:912, Y:603, Button:-2, Modifiers:0x0, Direction:0x0}
got mouse.Event{X:912, Y:603, Button:-2, Modifiers:0x0, Direction:0x0}
got mouse.Event{X:912, Y:603, Button:-2, Modifiers:0x0, Direction:0x0}
got mouse.Event{X:912, Y:603, Button:-2, Modifiers:0x0, Direction:0x0}
got mouse.Event{X:912, Y:603, Button:-2, Modifiers:0x0, Direction:0x0}
got mouse.Event{X:912, Y:603, Button:-2, Modifiers:0x0, Direction:0x0}
got mouse.Event{X:912, Y:603, Button:-2, Modifiers:0x0, Direction:0x0}
got mouse.Event{X:912, Y:603, Button:-2, Modifiers:0x0, Direction:0x0}
```

Those are the events I got in `basic` from scrolling with 2 fingers at a relatively slow speed about 1-2mm on the trackpad.

I get no events if I scroll 1 click with a physical mouse wheel, as I said, and these are the events I get if I scroll three clicks relatively quickly:

```
got mouse.Event{X:493, Y:538, Button:-2, Modifiers:0x0, Direction:0x0}
got mouse.Event{X:493, Y:538, Button:-2, Modifiers:0x0, Direction:0x0}
got mouse.Event{X:493, Y:538, Button:-2, Modifiers:0x0, Direction:0x0}
got mouse.Event{X:493, Y:538, Button:-2, Modifiers:0x0, Direction:0x0}
got mouse.Event{X:493, Y:538, Button:-2, Modifiers:0x0, Direction:0x0}
got mouse.Event{X:493, Y:538, Button:-2, Modifiers:0x0, Direction:0x0}
got mouse.Event{X:493, Y:538, Button:-2, Modifiers:0x0, Direction:0x0}
got mouse.Event{X:493, Y:538, Button:-2, Modifiers:0x0, Direction:0x0}
got mouse.Event{X:493, Y:538, Button:-2, Modifiers:0x0, Direction:0x0}
got mouse.Event{X:493, Y:538, Button:-2, Modifiers:0x0, Direction:0x0}
got mouse.Event{X:493, Y:538, Button:-2, Modifiers:0x0, Direction:0x0}
got mouse.Event{X:493, Y:538, Button:-2, Modifiers:0x0, Direction:0x0}
got mouse.Event{X:493, Y:538, Button:-2, Modifiers:0x0, Direction:0x0}
got mouse.Event{X:493, Y:538, Button:-2, Modifiers:0x0, Direction:0x0}
got mouse.Event{X:493, Y:538, Button:-2, Modifiers:0x0, Direction:0x0}
got mouse.Event{X:493, Y:538, Button:-2, Modifiers:0x0, Direction:0x0}
got mouse.Event{X:493, Y:538, Button:-2, Modifiers:0x0, Direction:0x0}
got mouse.Event{X:493, Y:538, Button:-2, Modifiers:0x0, Direction:0x0}
got mouse.Event{X:493, Y:538, Button:-2, Modifiers:0x0, Direction:0x0}
got mouse.Event{X:493, Y:538, Button:-2, Modifiers:0x0, Direction:0x0}
got mouse.Event{X:493, Y:538, Button:-2, Modifiers:0x0, Direction:0x0}
got mouse.Event{X:493, Y:538, Button:-2, Modifiers:0x0, Direction:0x0}
got mouse.Event{X:493, Y:538, Button:-2, Modifiers:0x0, Direction:0x0}
got mouse.Event{X:493, Y:538, Button:-2, Modifiers:0x0, Direction:0x0}
got mouse.Event{X:493, Y:538, Button:-2, Modifiers:0x0, Direction:0x0}
got mouse.Event{X:493, Y:538, Button:-2, Modifiers:0x0, Direction:0x0}
got mouse.Event{X:493, Y:538, Button:-2, Modifiers:0x0, Direction:0x0}
got mouse.Event{X:493, Y:538, Button:-2, Modifiers:0x0, Direction:0x0}
got mouse.Event{X:493, Y:538, Button:-2, Modifiers:0x0, Direction:0x0}
got mouse.Event{X:493, Y:538, Button:-2, Modifiers:0x0, Direction:0x0}
got mouse.Event{X:493, Y:538, Button:-2, Modifiers:0x0, Direction:0x0}
got mouse.Event{X:493, Y:538, Button:-2, Modifiers:0x0, Direction:0x0}
got mouse.Event{X:493, Y:538, Button:-2, Modifiers:0x0, Direction:0x0}
got mouse.Event{X:493, Y:538, Button:-2, Modifiers:0x0, Direction:0x0}
got mouse.Event{X:493, Y:538, Button:-2, Modifiers:0x0, Direction:0x0}
got mouse.Event{X:493, Y:538, Button:-2, Modifiers:0x0, Direction:0x0}
got mouse.Event{X:493, Y:538, Button:-2, Modifiers:0x0, Direction:0x0}
got mouse.Event{X:493, Y:538, Button:-2, Modifiers:0x0, Direction:0x0}
got mouse.Event{X:493, Y:538, Button:-2, Modifiers:0x0, Direction:0x0}
got mouse.Event{X:493, Y:538, Button:-2, Modifiers:0x0, Direction:0x0}
got mouse.Event{X:493, Y:538, Button:-2, Modifiers:0x0, Direction:0x0}
got mouse.Event{X:493, Y:538, Button:-2, Modifiers:0x0, Direction:0x0}
got mouse.Event{X:493, Y:538, Button:-2, Modifiers:0x0, Direction:0x0}
got mouse.Event{X:493, Y:538, Button:-2, Modifiers:0x0, Direction:0x0}
got mouse.Event{X:493, Y:538, Button:-2, Modifiers:0x0, Direction:0x0}
got mouse.Event{X:493, Y:538, Button:-2, Modifiers:0x0, Direction:0x0}
got mouse.Event{X:493, Y:538, Button:-2, Modifiers:0x0, Direction:0x0}
got mouse.Event{X:493, Y:538, Button:-2, Modifiers:0x0, Direction:0x0}
got mouse.Event{X:493, Y:538, Button:-2, Modifiers:0x0, Direction:0x0}
got mouse.Event{X:493, Y:538, Button:-2, Modifiers:0x0, Direction:0x0}
got mouse.Event{X:493, Y:538, Button:-2, Modifiers:0x0, Direction:0x0}
got mouse.Event{X:493, Y:538, Button:-2, Modifiers:0x0, Direction:0x0}
got mouse.Event{X:493, Y:538, Button:-2, Modifiers:0x0, Direction:0x0}
got mouse.Event{X:493, Y:538, Button:-2, Modifiers:0x0, Direction:0x0}
got mouse.Event{X:493, Y:538, Button:-2, Modifiers:0x0, Direction:0x0}
got mouse.Event{X:493, Y:538, Button:-2, Modifiers:0x0, Direction:0x0}
got mouse.Event{X:493, Y:538, Button:-2, Modifiers:0x0, Direction:0x0}
got mouse.Event{X:493, Y:538, Button:-2, Modifiers:0x0, Direction:0x0}
got mouse.Event{X:493, Y:538, Button:-2, Modifiers:0x0, Direction:0x0}
```

I can change the number of pixels that are scroll event moves from 50 pixels to 7 (a magic number that I thought I remembered seeing in cocoa.m, but can't find now..), but then a scroll event wouldn't scroll nearly enough under X11 or other drivers.

**Comment by driusan** [comment] 2016-06-22 17:45
I think the only two real driver problems are golang/go#16152 and golang/go#16020. 

The rest of the bugginess is on my end and/or I can work around with build tags.

**Closed** 2016-07-06 01:18 UTC
Labels: bug, driver bug?

**Comment by driusan** [comment] 2016-07-06 01:19
The `de` side of this should be fixed now. As far as I know, all that's outstanding is golang/go#16152. If you notice any other problems, file a new ticket..
