### ISSUE TITLE
memory leak

### ISSUE THREAD

**Issue by us3r64** [driusan/de#6] opened 2016-05-20 12:24 UTC
it looks like you have some memory leaks in there:

![de](https://cloud.githubusercontent.com/assets/531155/15427547/9000cee2-1e9e-11e6-9e79-b702b92c70d8.jpg)

**Comment by driusan** [comment] 2016-05-20 13:41
Ouch, that definitely looks worse than it should. I'm trying to reproduce and can't get it higher than around 230mb. I'll have to find a good valgrind-like tool for Go..

Some questions to reproduce in case I need to track it down manually:
1. How big is the file you're editing?
2. How long was the editor session open? (My typical work flow involves quitting to a shell pretty often, which might explain why I didn't see this..)
3. What OS, in case it's a bug in a downstream driver? (Looks like Mac?)
4. Were you doing a lot of editing or just browsing source code? If editing: inserting or deleting? If browsing: about how many files had you gone through to get the memory usage this high?
5. What version of Go are you using? (I think there's been pretty significant improvements to the GC in the last couple releases..)

**Comment by us3r64** [comment] 2016-05-20 14:39
1. file size 76KB - 2838 lines
2. the memory goes up to 6 GB right away after opening the file and pressing j a few times
3. OS X 10.11.5 (15F34)
4. just browsing, moving up and down (j,k), 1 file opened 
6. go version go1.6.2 darwin/amd64

**Comment by driusan** [comment] 2016-05-20 19:31
I don't think it's a memory leak. What I'm seeing with smaller files is that when I move around it takes a few renders (and j,k is triggering the render code since it needs to move where the cursor is drawn) before the Go GC kicks in.

I'm afraid to ask what you're doing with 76kb of source code in a single file (the biggest one in de is ~3kb), but I think writing the text in it to an RGBA image that can be drawn on the window is so large means that 5-6x that is getting out of hand and (and probably swapping before the GC has a chance to kick in?)

What I'll have to do is make sure the rendering code is smart enough to only render the part of the file that's being drawn to the screen so that it's invariant of file size, which is something I've been meaning to do anyways, but with my smaller files it's been fast enough to not be a significant issue.

Is the code that you're viewing open source or available somewhere that I can use as a test case?

**Comment by Komosa** [comment] 2016-05-20 21:12
Try this one: https://github.com/shurcooL/Conception-go/blob/665082e232068d054ec53e3d43680b0f8be2b456/main.go

**Comment by us3r64** [comment] 2016-05-20 21:55
Same issue. Looks that with file size memory used grows exponentially.

**Comment by driusan** [comment] 2016-05-21 01:02
I just commited something that should fix this. Can you try it and let me know if it worked?

The speed of the rendering (and responsiveness of the keyboard as a result) is still proportional to the file size, but now it's only allocating an image the size of the window, so the memory usage should be constant (or at least a function of the window size instead of the file size..)

**Comment by us3r64** [comment] 2016-05-23 10:02
Same behavior using the main.go file from @Komosa

**Comment by driusan** [comment] 2016-05-24 01:00
@us3r64 Did you update to the latest code? The excess memory consumption should be fixed in the latest version if you update with `go get -u github.com/driusan/de`, but yes, @Komosa's linked is big enough to have broken with the old version.

**Comment by us3r64** [comment] 2016-05-24 17:12
Looks to be fixed now.

**Closed** 2016-05-25 00:38 UTC
Labels: bug
